/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cab;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author tarun
 */
public class AddCompany extends javax.swing.JFrame {

    /**
     * Creates new form AddCompany
     */
    public AddCompany() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        companyname = new javax.swing.JTextField();
        addcompany = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("Added company");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("**press only once after software started**");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 370));
        setPreferredSize(new java.awt.Dimension(600, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 350));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("List of added company");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 110, 160, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Company name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 170, 160, 30);
        getContentPane().add(companyname);
        companyname.setBounds(250, 170, 230, 30);

        addcompany.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addcompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----select------" }));
        addcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcompanyActionPerformed(evt);
            }
        });
        getContentPane().add(addcompany);
        addcompany.setBounds(250, 110, 230, 30);

        jButton1.setText("Add company");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 220, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CAR_WALE.COM");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 20, 240, 30);

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(370, 220, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\New folder\\46725114-car-hd-wallpaper.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 600, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String s=companyname.getText().trim();
        Connection conn= null;
        Statement smt= null;
        ResultSet rst=null;
        try{
            conn=DBConnection.getConnection();
	    smt=conn.createStatement();
            String sql= "insert into company (name) values ("+"'"+s+"')";
           int r=smt.executeUpdate(sql);
            if(r>0){
               
        int n= addcompany.getItemCount();
        for(int i=0;i<=n;i++){
            String p= addcompany.getItemAt(i);
            if(s.equals(p)){
                
                JOptionPane.showMessageDialog(this,"company already added");
                addcompany.removeItemAt(i);
			   	companyname.requestFocus();
			   	return;
            }
        }
      
        addcompany.addItem(s); JOptionPane.showMessageDialog(this,"company added");
			   	companyname.requestFocus();
                                companyname.setText("");
        
        
                
              }
              
            
            
            
            
        }
        	catch(Exception e){
			e.printStackTrace();
		}
		finally{
			try{
				if(rst!=null)rst.close();
				if(smt!=null)smt.close();
				if(conn!=null)conn.close();
			}catch(Exception e){
				e.printStackTrace();
			}
		}
        
        



        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   Connection conn= null;
        Statement smt= null;
        ResultSet rst=null;
        
try{
 conn=DBConnection.getConnection();
	    smt=conn.createStatement();
            
            String sql1="select name from company";
            rst=smt.executeQuery(sql1);
            while(rst.next()){
                addcompany.addItem(rst.getString("name"));
                
            }   



}



catch(Exception e){
			e.printStackTrace();
		}
		finally{
			try{
				if(rst!=null)rst.close();
				if(smt!=null)smt.close();
				if(conn!=null)conn.close();
			}catch(Exception e){
				e.printStackTrace();
			}
		}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       
        new AdminPage().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_cancelActionPerformed

    private void addcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcompanyActionPerformed
      showCar();
      addcompany.setEditable(false);
    }//GEN-LAST:event_addcompanyActionPerformed
   public void showCar(){
          Connection conn= null;
        Statement smt= null;
        ResultSet rst=null;
        
try{
 conn=DBConnection.getConnection();
	    smt=conn.createStatement();
            
            String sql1="select name from company";
            rst=smt.executeQuery(sql1);
            while(rst.next()){
                addcompany.addItem(rst.getString("name"));
                
            }   



}



catch(Exception e){
			e.printStackTrace();
		}
		finally{
			try{
				if(rst!=null)rst.close();
				if(smt!=null)smt.close();
				if(conn!=null)conn.close();
			}catch(Exception e){
				e.printStackTrace();
			}
		}
       
       
       
       
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> addcompany;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField companyname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
