/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cab;
import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author tarun
 */
public class AddDriver extends javax.swing.JFrame {
      
    String s,data;
    
    /**
     * Creates new form AddDriver
     */
    public AddDriver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        MyTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        pic = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Mytable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        addCompany = new javax.swing.JComboBox<>();
        sitting = new javax.swing.JComboBox<>();
        cNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        MyTable.setBackground(new java.awt.Color(0, 0, 0));
        MyTable.setForeground(new java.awt.Color(255, 255, 255));
        MyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "carmodel", "comapny", "carnumber", "makeyear", "useas", "sitting", "engine", "type", "varient", "rent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(MyTable);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1052, 580));
        setPreferredSize(new java.awt.Dimension(1052, 580));
        setResizable(false);
        setSize(new java.awt.Dimension(1052, 580));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Driver Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 50, 70, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 50, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 160, 60, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 200, 60, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Phone no");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 310, 60, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Date of joining");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 410, 100, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Experience");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 360, 90, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DOB");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 460, 40, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 40, 180, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 100, 180, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----select----", "Male", "Female" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(150, 150, 120, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 200, 180, 70);

        jButton1.setText("choose photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 190, 110, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----select------", "no experience", "1-2 year", "2-3 year", "3-4 year", "4-5 year", "more than 5 year" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(150, 350, 120, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(150, 300, 180, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(150, 400, 180, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(150, 450, 180, 30);

        pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pic.setOpaque(false);
        pic.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pic);
        pic.setBounds(400, 10, 150, 160);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 500, 140, 40);

        Mytable.setBackground(new java.awt.Color(0, 0, 0));
        Mytable.setForeground(new java.awt.Color(255, 255, 255));
        Mytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "carmodel", "company", "carNo", "makeYear", "sitting", "engine", "type", "varient"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Mytable.setCellSelectionEnabled(true);
        ListSelectionModel select= Mytable.getSelectionModel();
        select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        select.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String Data = null;
                int[] row = Mytable.getSelectedRows();
                int[] columns = Mytable.getSelectedColumns();
                for (int i = 0; i < row.length; i++) {
                    for (int j = 0; j < columns.length; j++) {
                        Data = (String) Mytable.getValueAt(row[i], columns[j]);
                    } }
                    cNo.setText(Data);
                }
            });
            Mytable.setOpaque(false);
            jScrollPane5.setViewportView(Mytable);
            if (Mytable.getColumnModel().getColumnCount() > 0) {
                Mytable.getColumnModel().getColumn(0).setResizable(false);
                Mytable.getColumnModel().getColumn(1).setResizable(false);
                Mytable.getColumnModel().getColumn(2).setResizable(false);
                Mytable.getColumnModel().getColumn(3).setResizable(false);
                Mytable.getColumnModel().getColumn(4).setResizable(false);
                Mytable.getColumnModel().getColumn(5).setResizable(false);
                Mytable.getColumnModel().getColumn(6).setResizable(false);
                Mytable.getColumnModel().getColumn(7).setResizable(false);
            }

            getContentPane().add(jScrollPane5);
            jScrollPane5.setBounds(540, 210, 490, 210);

            jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel10.setForeground(new java.awt.Color(255, 255, 255));
            jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel10.setText("select company");
            jLabel10.setToolTipText("");
            getContentPane().add(jLabel10);
            jLabel10.setBounds(590, 30, 110, 17);

            jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel11.setForeground(new java.awt.Color(255, 255, 255));
            jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel11.setText("sitting");
            getContentPane().add(jLabel11);
            jLabel11.setBounds(860, 20, 70, 20);

            jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel12.setForeground(new java.awt.Color(255, 255, 255));
            jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel12.setText("car no");
            getContentPane().add(jLabel12);
            jLabel12.setBounds(590, 84, 60, 30);

            jButton3.setText("cars available");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton3);
            jButton3.setBounds(910, 90, 110, 30);

            addCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------select-------" }));
            addCompany.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    addCompanyActionPerformed(evt);
                }
            });
            getContentPane().add(addCompany);
            addCompany.setBounds(710, 20, 120, 30);

            sitting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------select---------", "2 seater", "5 seater", "7 seater", "8 seater", "11 seater" }));
            getContentPane().add(sitting);
            sitting.setBounds(910, 20, 100, 30);
            getContentPane().add(cNo);
            cNo.setBounds(710, 90, 110, 30);

            jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(255, 255, 255));
            jLabel9.setIcon(new javax.swing.ImageIcon("D:\\New folder\\black_background_wood_darker-wallpaper-1920x1200.jpg")); // NOI18N
            jLabel9.setText("jLabel9");
            getContentPane().add(jLabel9);
            jLabel9.setBounds(0, 0, 1050, 560);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
       
           JFileChooser fc = new JFileChooser();
                int result = fc.showOpenDialog(null);
                if (result == JFileChooser.APPROVE_OPTION) {
                    File file = fc.getSelectedFile();
                    String path= file.getAbsolutePath();
                    System.err.println(path);
                    JLabel image = new JLabel("", new ImageIcon(path), JLabel.CENTER);
                    pic.add(image, BorderLayout.CENTER);
                    pic.revalidate(); //ADD THIS AS WELL
                    pic.repaint();  //ADD THIS AS WELL
                   s=path;
                    //s.replace('\\','/');
                      //System.err.println(s);
                }
         
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        try {
            add();
        } catch (FileNotFoundException | SQLException ex) {
            Logger.getLogger(AddDriver.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompanyActionPerformed
       
         String str=addCompany.getSelectedItem().toString();
        
     if(str.equals("------select-------"))
     {  
         showCar();
     
     }  
        
        
    }//GEN-LAST:event_addCompanyActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        showTable();
        
    }//GEN-LAST:event_jButton3ActionPerformed
   
    
    
     
     
    

    
    
    
    
    
    
    
    
    
     public void showTable(){
        DefaultTableModel dtm = new DefaultTableModel();
        Connection conn=null;
	Statement stmt=null;
	ResultSet rset=null;
        
        try{
            
            	String companyName =addCompany.getSelectedItem().toString();
                String use= sitting.getSelectedItem().toString();
                //String varients= varient.getSelectedItem().toString();
                if(companyName.equals("------select-------")||use.equals("--------select---------"))
                {
                    JOptionPane.showMessageDialog(this,"please select the field");
                }
                else{  
                
                conn = DBConnection.getConnection();
		stmt= conn.createStatement();
                String sql= "select * from service where company ='"+companyName+"'  and sitting_capacity='"+use+"'";
                rset = stmt.executeQuery(sql);
                
               
                          while(Mytable.getRowCount() > 0) 
        {
            ((DefaultTableModel) Mytable.getModel()).removeRow(0);
        }
        int columns = rset.getMetaData().getColumnCount();
        while(rset.next())
        {  
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++)
            {  
                row[i - 1] = rset.getObject(i);
            }
            ((DefaultTableModel) Mytable.getModel()).insertRow(rset.getRow()-1,row);
        }

                }            
            
 }
    
               catch(Exception e){
            System.err.println(e);
        }
        finally{
            try{
                rset.close();
                stmt.close();
                conn.close();
            }
            catch(Exception e){
            }
        }
        
            
        
        
        
        
    }
    
    
    
    
    
    
         public void showCar(){
          
         Connection conn= null;
          Statement smt= null;
          ResultSet rst=null;
        
try{
 conn=DBConnection.getConnection();
	    smt=conn.createStatement();
            
            String sql1="select name from company";
            rst=smt.executeQuery(sql1);
            while(rst.next()){
                addCompany.addItem(rst.getString("name"));
                
            }   



}



catch(Exception e){
		}
		finally{
			try{
				if(rst!=null)rst.close();
				if(smt!=null)smt.close();
				if(conn!=null)conn.close();
			}catch(Exception e){
			}
		}
       
       
       
       
   }
    
    
    
    
    
    public void add() throws FileNotFoundException, SQLException{
        
          Connection conn=null;
     Statement stmt=null;
      
     try{
         
         String Driver=jTextField1.getText().trim();
         String name= jTextField2.getText().trim();
         String gen=jComboBox1.getSelectedItem().toString();
         String add=jTextArea1.getText().trim();
         String phone=jTextField3.getText().trim();
         String exp=jComboBox2.getSelectedItem().toString();
         String dob=jTextField4.getText().trim();
         String doj=jTextField5.getText().trim();
         String car=cNo.getText().trim();
         String dummy="YES";
         
         
         	conn=DBConnection.getConnection();
		stmt=conn.createStatement();
                //InputStream is = new FileInputStream(new File(s));
                String sql1="update service SET driverId='"+Driver+"',driver='"+dummy+"' WHERE car_number='"+car+"'";
                String sql="insert into addDriver(driver_id,name,gender,address,phone_no,experience,date_of,doj,photo) values("+
                        "'"+Driver+"','"+name+"','"+gen+"','"+add+"','"+phone+"','"+exp+"','"+dob+"','"+doj+"','"+s+"')";
                        
                int rowAffected = stmt.executeUpdate(sql);
                int rw1=stmt.executeUpdate(sql1);
                 if(rowAffected>0){
                             JOptionPane.showMessageDialog(this,"Driver added successfully");
                             
                         }
                         else
                             JOptionPane.showMessageDialog(this,"some problem in data");        
                        
         
       }
     
                         	catch(SQLException | HeadlessException e){
		}
		finally{
			try{
				if(stmt!=null)stmt.close();
				if(conn!=null)conn.close();
			}
			catch(Exception e){
				e.printStackTrace();
			}
		}
     
        
        
        
        
        
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MyTable;
    private javax.swing.JTable Mytable;
    private javax.swing.JComboBox<String> addCompany;
    private javax.swing.JTextField cNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel pic;
    private javax.swing.JComboBox<String> sitting;
    // End of variables declaration//GEN-END:variables
}
