/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cab;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;

/**
 *
 * @author tarun
 */
public class AddVehicle extends javax.swing.JFrame {

    /**
     * Creates new form AddVehicle
     */
    public AddVehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        use = new javax.swing.JComboBox<>();
        addcompany = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        capacity = new javax.swing.JComboBox<>();
        engine = new javax.swing.JTextField();
        varient = new javax.swing.JComboBox<>();
        rent = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(780, 550));
        setPreferredSize(new java.awt.Dimension(780, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(780, 550));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("car model");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 140, 70, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("company");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 200, 70, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("car number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 260, 71, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("make year");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 310, 70, 17);

        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });
        getContentPane().add(model);
        model.setBounds(220, 140, 140, 30);
        getContentPane().add(number);
        number.setBounds(220, 250, 140, 30);
        getContentPane().add(year);
        year.setBounds(220, 300, 140, 30);

        use.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------select------", "taxi", "individual rent" }));
        getContentPane().add(use);
        use.setBounds(220, 350, 140, 30);

        addcompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------select---------" }));
        addcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcompanyActionPerformed(evt);
            }
        });
        getContentPane().add(addcompany);
        addcompany.setBounds(220, 200, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("sitting capacity");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 140, 100, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("engine capacity");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 190, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Type");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(460, 260, 80, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("varient");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(460, 310, 70, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("rent");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(460, 360, 70, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 450, 120, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("use as");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 360, 80, 17);

        capacity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------select---------", "2 seater", "5 seater", "7 seater", "8 seater", "11 seater" }));
        getContentPane().add(capacity);
        capacity.setBounds(580, 140, 130, 30);
        getContentPane().add(engine);
        engine.setBounds(580, 200, 130, 30);

        varient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------select--------", "base model", "economic model", "top model" }));
        getContentPane().add(varient);
        varient.setBounds(580, 300, 130, 30);
        getContentPane().add(rent);
        rent.setBounds(580, 350, 130, 30);

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------select-------", "ac", "non-ac" }));
        getContentPane().add(type);
        type.setBounds(580, 250, 130, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Add Vehicle");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(310, 40, 250, 50);

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\New folder\\back-button.png")); // NOI18N
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 50, 140, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\New folder\\background-images-for-websites-23.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-60, 0, 900, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelActionPerformed

    private void addcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcompanyActionPerformed
     
        showCar();
          
    }//GEN-LAST:event_addcompanyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        addVehicle();      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    new AdminPage().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void addVehicle(){
        
        Connection conn= null;
        Statement stmt=null;
        
        try{
            
            String carModel= model.getText().trim();
            String company= addcompany.getSelectedItem().toString();
            String carNumber=number.getText().trim();
            String makeYear= year.getText().trim();
            String useAs=use.getSelectedItem().toString();
            String sittingCapacity=capacity.getSelectedItem().toString();
            String engineCapacity=engine.getText().trim();
            String Vtype=type.getSelectedItem().toString();
            String Vvarient=varient.getSelectedItem().toString();
            String Vrent=rent.getText().trim();
            
            if(carModel.equals("")){
				JOptionPane.showMessageDialog(this,"Fill carModel");
				model.requestFocus();
				return;
			}else if(company.equals("---------select---------")){
				JOptionPane.showMessageDialog(this,"select company name");
				addcompany.requestFocus();
				return;
			}else if(carNumber.equals("")){
				JOptionPane.showMessageDialog(this,"Fill car no ");
				number.requestFocus();
				return;
			}else if(makeYear.equals("")){
				JOptionPane.showMessageDialog(this,"Fill make year");
				year.requestFocus();
				return;
			}else if(useAs.equals("-------select------")){
			   	JOptionPane.showMessageDialog(this,"Fill useAs");
			   	use.requestFocus();
			   	return;
			}else if(sittingCapacity.equals("--------select---------")){
				JOptionPane.showMessageDialog(this,"Fill sitting capacity");
				capacity.requestFocus();
				return;
			}
			else if(engineCapacity.equals("")){
				JOptionPane.showMessageDialog(this,"Fill engine capacity");
				engine.requestFocus();
				return;
			}
            else if(Vtype.equals("---------select-------")){
				JOptionPane.showMessageDialog(this,"Fill type");
				type.requestFocus();
				return;
			}
            else if(Vvarient.equals("--------select--------")){
				JOptionPane.showMessageDialog(this,"Fill varients");
				varient.requestFocus();
				return;
			}
               else if(Vrent.equals(" ")){
				JOptionPane.showMessageDialog(this,"Fill rent");
				rent.requestFocus();
				return;
			}
            
            
            
            	conn=DBConnection.getConnection();
		stmt=conn.createStatement();
                String sql="insert into service(car_model,company,car_number,make_year,use_as,sitting_capacity,engine_capacity,type,varient,fare) values"
                        + "("+"'"+carModel+"','"+company+"','"+carNumber+"','"+makeYear+"','"+useAs+"','"+sittingCapacity+"','"+engineCapacity+"','"+Vtype+"','"+Vvarient+"','"+Vrent+"')";        
            
               int row=stmt.executeUpdate(sql);
               if(row>0){
                   
                   JOptionPane.showMessageDialog(this,"vehicle added successfully");
                   
               }
               else
                   JOptionPane.showMessageDialog(this,"some problem in data");
            
            
 }
        
                      	catch(Exception e){
			e.printStackTrace();
		}
		finally{
			try{
				if(stmt!=null)stmt.close();
				if(conn!=null)conn.close();
			}
			catch(Exception e){
				e.printStackTrace();
			}
		}
        
        
        
        
        
        
        
        
        
        
    }
    
    
       public void showCar(){
          Connection conn= null;
        Statement smt= null;
        ResultSet rst=null;
        
try{
 conn=DBConnection.getConnection();
	    smt=conn.createStatement();
            
            String sql1="select name from company";
            rst=smt.executeQuery(sql1);
            while(rst.next()){
                addcompany.addItem(rst.getString("name"));
                
            }   



}



catch(Exception e){
			e.printStackTrace();
		}
		finally{
			try{
				if(rst!=null)rst.close();
				if(smt!=null)smt.close();
				if(conn!=null)conn.close();
			}catch(Exception e){
				e.printStackTrace();
			}
		}
       
       
       
       
   }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> addcompany;
    private javax.swing.JComboBox<String> capacity;
    private javax.swing.JTextField engine;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField model;
    private javax.swing.JTextField number;
    private javax.swing.JTextField rent;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JComboBox<String> use;
    private javax.swing.JComboBox<String> varient;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
