/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cab;
import javax.swing.*;
import java.sql.*;
/**
 *
 * @author tarun
 */
public class EmployeeLogin extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeLogin
     */
    public EmployeeLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        empPass = new javax.swing.JPasswordField();
        empId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(560, 350));
        setSize(new java.awt.Dimension(560, 350));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("emp-id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 120, 90, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 170, 58, 17);

        empPass.setOpaque(false);
        empPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPassActionPerformed(evt);
            }
        });
        getContentPane().add(empPass);
        empPass.setBounds(300, 170, 230, 30);

        empId.setOpaque(false);
        getContentPane().add(empId);
        empId.setBounds(300, 120, 230, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Employee Login");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 10, 150, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\New folder\\download.png")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 100, 150, 160);

        jButton1.setText("cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 240, 80, 30);

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 240, 80, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\New folder\\51fa7e52365f8fb89c69531ab92959bb.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, -70, 560, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    checkLogin();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new login().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void checkLogin(){
        
        
             Connection conn=null;
	Statement stmt=null;
	ResultSet rset=null;
        
        try{
            
            String empid= empId.getText().trim();
            String password=empPass.getText().trim();
            if(empid.equals("")){
				JOptionPane.showMessageDialog(this,"Fill UserId !");
			   	empId.requestFocus();
			   	return;
			}else if(password.equals("")){
			 	JOptionPane.showMessageDialog(this,"Fill Pssword !");
			   	empPass.requestFocus();
			   	return;
			}
        conn=DBConnection.getConnection();
        stmt=conn.createStatement();
			String sql="select * from addemployee where  user_name='"+empid+"' and password='"+password+"'";
		  	rset =	 stmt.executeQuery(sql);
                        
                        if(rset.next()){
                             String s= rset.getString("name");
                             String m= "Welcome Mr " +s;
                             JOptionPane.showMessageDialog(this,"login successfully");
                             EmployeePage a= new EmployeePage(m);
                             a.setVisible(true);
                             this.dispose();
                             
                             
                            
                            
                            
                            
                        }
                        else{
		   	   	JOptionPane.showMessageDialog(this,"Invalid UserName OR Password !");
		   	}
                        
  }
        
        catch(Exception e){
			e.printStackTrace();
	   	   	JOptionPane.showMessageDialog(this,e.toString());
		}finally{
			try{
				if(rset!=null)rset.close();
				if(stmt!=null)stmt.close();
				if(conn!=null)conn.close();
			}catch(Exception e){
				e.printStackTrace();
			}
		}
	
        
        
        
        
        
        
        
        
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empId;
    private javax.swing.JPasswordField empPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
