/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cab;

import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tarun
 */
public class UpdateDriver extends javax.swing.JFrame {

    String s, data;

    /**
     * Creates new form AddDriver
     */
    public UpdateDriver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        MyTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        Mytable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        sitting = new javax.swing.JComboBox<>();
        addCompany = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pic = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        meri = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        MyTable.setBackground(new java.awt.Color(0, 0, 0));
        MyTable.setForeground(new java.awt.Color(255, 255, 255));
        MyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "carmodel", "comapny", "carnumber", "makeyear", "useas", "sitting", "engine", "type", "varient", "rent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(MyTable);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        Mytable.setBackground(new java.awt.Color(0, 0, 0));
        Mytable.setForeground(new java.awt.Color(255, 255, 255));
        Mytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "carmodel", "company", "carNo", "makeYear", "sitting", "engine", "type", "varient"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Mytable.setCellSelectionEnabled(true);
        ListSelectionModel select= Mytable.getSelectionModel();
        select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        select.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                String Data = null;
                int[] row = Mytable.getSelectedRows();
                int[] columns = Mytable.getSelectedColumns();
                for (int i = 0; i < row.length; i++) {
                    for (int j = 0; j < columns.length; j++) {
                        Data = (String) Mytable.getValueAt(row[i], columns[j]);
                    } }
                    cNo.setText(Data);
                }
            });
            Mytable.setOpaque(false);
            jScrollPane5.setViewportView(Mytable);
            if (Mytable.getColumnModel().getColumnCount() > 0) {
                Mytable.getColumnModel().getColumn(0).setResizable(false);
                Mytable.getColumnModel().getColumn(1).setResizable(false);
                Mytable.getColumnModel().getColumn(2).setResizable(false);
                Mytable.getColumnModel().getColumn(3).setResizable(false);
                Mytable.getColumnModel().getColumn(4).setResizable(false);
                Mytable.getColumnModel().getColumn(5).setResizable(false);
                Mytable.getColumnModel().getColumn(6).setResizable(false);
                Mytable.getColumnModel().getColumn(7).setResizable(false);
            }

            jButton3.setText("cars available");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            sitting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------select---------", "2 seater", "5 seater", "7 seater", "8 seater", "11 seater" }));

            addCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------select-------" }));
            addCompany.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    addCompanyActionPerformed(evt);
                }
            });

            jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel11.setForeground(new java.awt.Color(255, 255, 255));
            jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel11.setText("sitting");

            jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel12.setForeground(new java.awt.Color(255, 255, 255));
            jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel12.setText("car no");

            jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel10.setForeground(new java.awt.Color(255, 255, 255));
            jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel10.setText("select company");
            jLabel10.setToolTipText("");

            jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(255, 255, 255));
            jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel6.setText("Date of joining");

            pic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
            pic.setLayout(new java.awt.BorderLayout());

            jButton1.setText("choose photo");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setMinimumSize(new java.awt.Dimension(800, 500));
            setSize(new java.awt.Dimension(800, 500));
            getContentPane().setLayout(null);

            jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setText("Driver Id");
            getContentPane().add(jLabel1);
            jLabel1.setBounds(40, 50, 70, 17);

            jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("Name");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(40, 110, 50, 17);

            jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(255, 255, 255));
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel3.setText("Gender");
            getContentPane().add(jLabel3);
            jLabel3.setBounds(40, 160, 60, 17);

            jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel4.setText("Address");
            getContentPane().add(jLabel4);
            jLabel4.setBounds(40, 200, 60, 17);

            jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel5.setText("Phone no");
            getContentPane().add(jLabel5);
            jLabel5.setBounds(50, 310, 60, 17);

            jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(255, 255, 255));
            jLabel7.setText("Experience");
            getContentPane().add(jLabel7);
            jLabel7.setBounds(50, 360, 90, 17);

            jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(255, 255, 255));
            jLabel8.setText("DOB");
            getContentPane().add(jLabel8);
            jLabel8.setBounds(50, 420, 40, 17);
            getContentPane().add(jTextField1);
            jTextField1.setBounds(150, 40, 180, 30);
            getContentPane().add(jTextField2);
            jTextField2.setBounds(150, 100, 180, 30);

            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----select----", "Male", "Female" }));
            getContentPane().add(jComboBox1);
            jComboBox1.setBounds(150, 150, 120, 30);

            jTextArea1.setColumns(20);
            jTextArea1.setRows(5);
            jScrollPane1.setViewportView(jTextArea1);

            getContentPane().add(jScrollPane1);
            jScrollPane1.setBounds(150, 200, 180, 70);

            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----select------", "no experience", "1-2 year", "2-3 year", "3-4 year", "4-5 year", "more than 5 year" }));
            getContentPane().add(jComboBox2);
            jComboBox2.setBounds(150, 350, 120, 30);
            getContentPane().add(jTextField3);
            jTextField3.setBounds(150, 300, 180, 30);
            getContentPane().add(jTextField5);
            jTextField5.setBounds(150, 410, 180, 30);

            jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jButton2.setText("Update");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton2);
            jButton2.setBounds(430, 400, 120, 40);

            jButton4.setText("search");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });
            getContentPane().add(jButton4);
            jButton4.setBounds(370, 40, 100, 30);

            jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jButton5.setText("Delete");
            getContentPane().add(jButton5);
            jButton5.setBounds(590, 400, 110, 40);

            meri.setIcon(new javax.swing.ImageIcon("D:\\New folder\\placeholder-hi.png")); // NOI18N
            getContentPane().add(meri);
            meri.setBounds(550, 10, 180, 170);

            jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(255, 255, 255));
            jLabel9.setIcon(new javax.swing.ImageIcon("D:\\New folder\\blue_shades_abstract-HD.png")); // NOI18N
            jLabel9.setText("jLabel9");
            getContentPane().add(jLabel9);
            jLabel9.setBounds(0, -10, 810, 500);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser fc = new JFileChooser();
        int result = fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            String path = file.getAbsolutePath();
            JLabel image = new JLabel("", new ImageIcon(path), JLabel.CENTER);
            pic.add(image, BorderLayout.CENTER);
            pic.revalidate(); //ADD THIS AS WELL
            pic.repaint();  //ADD THIS AS WELL
            s = path;
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            add();
        } catch (FileNotFoundException | SQLException ex) {
            Logger.getLogger(UpdateDriver.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void addCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompanyActionPerformed


    }//GEN-LAST:event_addCompanyActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String userName = jTextField1.getText().trim();
        if (!userName.trim().equals("")) {

            getData(userName);

        } else {
            JOptionPane.showMessageDialog(this, "Plesase enter user name");
            jTextField1.requestFocus();
            return;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public void getData(String userName) {
        Connection conn = null;
        Statement stmt = null;
        ResultSet rset = null;

        try {
            conn = DBConnection.getConnection();
            stmt = conn.createStatement();
            String sql = "select * from adddriver where driver_id='" + userName + "'";
            rset = stmt.executeQuery(sql);

            if (rset.next()) {
                JOptionPane.showMessageDialog(this, "information fetched successfulyy!!");
                jTextField1.requestFocus();

                //	jTextField1.setText(rset.getString("driver_id"));
                jTextField2.setText(rset.getString("name"));
                jComboBox1.setSelectedItem(rset.getString("gender"));
                jTextArea1.setText(rset.getString("address"));
                jComboBox2.setSelectedItem(rset.getString("experience"));
                jTextField5.setText(rset.getString("doj"));
                jTextField3.setText(rset.getString("phone_no"));
                String g = rset.getString("photo");
                System.err.println(g);
                //JLabel images = new JLabel();
               meri.setIcon(new javax.swing.ImageIcon(g)); // NOI18N

 //  getContentPane().add(meri);
  meri.setBounds(550, 10, 180, 170);

                //pic.add(images, BorderLayout.CENTER);

                //pic.revalidate(); //ADD THIS AS WELL
                //pic.repaint();  //ADD THIS AS WELL

            } else {
                JOptionPane.showMessageDialog(this, "enter correct user name!!");
                jTextField1.requestFocus();

            }

        } catch (Exception e) {
            e.printStackTrace();

        } finally {
            try {
                if (rset != null) {
                    rset.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }

    public void add() throws FileNotFoundException, SQLException {

        Connection conn = null;
        Statement stmt = null;

        try {

            String Driver = jTextField1.getText().trim();
            String name = jTextField2.getText().trim();
            String gen = jComboBox1.getSelectedItem().toString();
            String add = jTextArea1.getText().trim();
            String phone = jTextField3.getText().trim();
            String exp = jComboBox2.getSelectedItem().toString();
            String dob = jTextField4.getText().trim();
            String doj = jTextField5.getText().trim();
            String car = cNo.getText().trim();
            String dummy = "YES";

            conn = DBConnection.getConnection();
            stmt = conn.createStatement();
            //InputStream is = new FileInputStream(new File(s));
            //String sql1="update service SET driverId='"+Driver+"',driver='"+dummy+"' WHERE car_number='"+car+"'";
            String sql = "update adddriver set driver_id='" + Driver + "',name='" + name + "',gender='" + gen + "',address='" + add + "',phone_no='" + phone + "',experience='" + exp
                    + "',doj='" + doj + "',photo='" + s + "' where driver_id='" + Driver + "'";

            int rowAffected = stmt.executeUpdate(sql);
            //int rw1=stmt.executeUpdate(sql1);
            if (rowAffected > 0) {
                JOptionPane.showMessageDialog(this, "Driver added successfully");

            } else {
                JOptionPane.showMessageDialog(this, "some problem in data");
            }

        } catch (SQLException | HeadlessException e) {
        } finally {
            try {
                if (stmt != null) {
                    stmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (Exception e) {
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UpdateDriver().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MyTable;
    private javax.swing.JTable Mytable;
    private javax.swing.JComboBox<String> addCompany;
    private javax.swing.JTextField cNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    public javax.swing.JLabel meri;
    private javax.swing.JPanel pic;
    private javax.swing.JComboBox<String> sitting;
    // End of variables declaration//GEN-END:variables
}
